Added documentation for pitfalls and best practises
zama-ai/fhevm-solidity pull request #276
Opened 2024-02-01 16:06 UTC by jatZama

2024-02-01 17:35 UTC, immortal-tofu requested changes

2024-02-01 17:35 UTC, immortal-tofu commented on docs/howto/pitfalls.md
> +  euint32 internal a = TFHE.asEuint32(42);
No, you can't call precompiles on properties

2024-02-01 17:35 UTC, immortal-tofu commented on docs/howto/pitfalls.md
> +Or else, this would expose the variabls to any external untrusted smart contract which could ask for decrypting them, losing confidentiality.
`Declaring an encrypted state variable as public exposes the variable to any external untrusted smart contract to access and potentially decrypt them, compromising their confidentiality.`

2024-02-01 17:35 UTC, immortal-tofu commented on docs/howto/pitfalls.md
> +If a view function is using `TFHE.reencrypt` it is mandatory to protect it via the `onlySignedPublicKey` modifier imported from `"fhevm/abstracts/Reencrypt.sol"`. See the example from the [Decrypt pa
`If you fail to do this, then anyone could reencrpyt anyone else's ciphertext, because when doing a static call to a view function you could impersonate any `msg.sender`'s address since no signature is needed, contrarily to transactions.`
=>
`Failing to address this allows anyone to reencrypt another person's ciphertext. This vulnerability comes from the ability to impersonate any msg.sender address during a static call to a view function, as it does not require a signature, unlike transactions.`

2024-02-01 17:35 UTC, immortal-tofu commented on docs/howto/pitfalls.md
> +## Avoid using TFHE.decrypt, use CMUX instead when possible
`Avoid using TFHE.decrypt, use TFHE.cmux instead`

2024-02-01 17:35 UTC, immortal-tofu commented on docs/howto/pitfalls.md
> +Please also not that the optimistic require operator `TFHE.optReq` is also deprecated: we recommend to avoid its use in all cases.
I'd remove this sentence because this is not related to the topic (decrypt).

Create a specific section for optReq or simply remove all mentions from the documentation?

2024-02-01 17:35 UTC, immortal-tofu commented on docs/howto/pitfalls.md
> +In the previous paragraph, we already saw that branching logic depending on ciphertexts should rely as much as possible on CMUX operators instead of decryptions, in order to hide which branch has bee
`The previous paragraph emphasized that branch logic should rely as much as possible on TFHE.cmux instead of decryptions. It hides effectively which branch has been executed.`

2024-02-01 17:35 UTC, immortal-tofu commented on docs/howto/pitfalls.md
> +But this is sometimes not enough. Naive application of FHE operations can still leak a lot of information. Adding privacy to smart contracts require revisiting sometimes the logic of your application
`However, this is sometimes not enough. Enhancing the privacy of smart contracts often requires revisiting your application's logic.`

2024-02-01 17:35 UTC, immortal-tofu commented on docs/howto/pitfalls.md
> +If your code logic requires looping on an encrypted boolean condition, we highly suggest to try to replace it by a finite loop with an appropriate constant maximum number of steps and use CMUX inside
`TFHE.cmux`

2024-02-01 17:35 UTC, immortal-tofu commented on docs/howto/pitfalls.md
> +However, there are plans to make this kind of operation much more efficient on the roadmap, using a specialized operator for arrays.
I wouldn't talk about roadmap here because we'll probably forget to update this here. We have a specific roadmap page for this.

2024-02-01 17:35 UTC, immortal-tofu commented on docs/howto/pitfalls.md
> +For example, let's say you have an encrypted array variable `encArray` and want to set some encrypted state variable `x` to be equal to some element `encArray[i]`, _without_ disclosing the index `i`.
`For instance, imagine you have an encrypted array called `encArray` and you want to update an encrypted value `x` to match an item from this list, encArray[i], without disclosing which item you're choosing.`

2024-02-01 17:35 UTC, immortal-tofu commented on docs/howto/pitfalls.md
> +❌ For the moment, you must loop over all the indexes and check equality homomorphically, however this pattern is very expensive in gas and should be avoided whenever possible.
Remove `For the moment`

`You must loop over all the indexes and check equality homomorphically, however this pattern is very expensive in gas and should be avoided whenever possible.`

2024-02-01 17:35 UTC, immortal-tofu commented on docs/howto/pitfalls.md
> +✅ But you can fix this issue by using CMUX to cancel the mint in case of an overflow:
`TFHE.cmux`

2024-02-01 17:35 UTC, immortal-tofu commented on docs/howto/pitfalls.md
> +# Typical workflow for writing confidential smart contracts on the fhEVM
It's probably something we should rewrite and move to the `Getting started` page. Something which link to the subpages hardhat/remix/...

2024-02-01 17:35 UTC, immortal-tofu commented on docs/howto/pitfalls.md
> +❌ This kind of loop should be absolutely avoided, because it relies potentially on a huge number of decrypts, and even a single decrypt should be avoided in general:
`Avoid using this type of loop because it might require many decryption operations:`

2024-02-01 17:35 UTC, immortal-tofu commented on docs/howto/pitfalls.md
> +✅ But write instead:
Instead, you should describe your property as follow:

2024-02-01 17:35 UTC, immortal-tofu commented on docs/howto/pitfalls.md
> +This means that you should avoid trivial encryptions when possible.
I'd remove this sentence, seems redudant

2024-02-01 18:18 UTC, jatZama commented on docs/howto/pitfalls.md
> +  euint32 internal a = TFHE.asEuint32(42);
I do not understand your review : I just tried this code and it works without problem on Zama Remix IDE fyi. 
```solidity
pragma solidity ^0.8.20;

import "fhevm/lib/TFHE.sol";

contract C {
    euint32 internal a = TFHE.asEuint32(42);
    function getA() public view returns(uint32) {
        return TFHE.decrypt(a);
    }
}
```

The important thing to make everything working is to remove the constant/immutable keyword to let the TFHE computation and storage in privileged storage happen at construction time.

2024-02-01 18:20 UTC, immortal-tofu commented on docs/howto/pitfalls.md
> +  euint32 internal a = TFHE.asEuint32(42);
Ho I didn't know it was just the keywords `immutable` blocking. I thought it was totally forbidden. My bad in this case 🙏

2024-02-01 18:40 UTC, jatZama commented on docs/howto/pitfalls.md
> +✅ But write instead:
"Instead, you should declare the state variable as follow:" seems even better here, wdyt?

2024-02-01 20:30 UTC, immortal-tofu requested changes

2024-02-01 20:30 UTC, immortal-tofu commented on docs/getting_started/workflow.md
> +# Typical workflow for writing confidential smart contracts
Sorry I wasn't clear: what I thought was to add this section in the getting started page for contract => https://docs.zama.ai/fhevm/how-to/write_contract
It could be a section below `Installation` where we introduce the 2 subpages (Hardhat and Remix) and emphasizes that developer should use the template. We have so many issues because users start with their own custom hardhat template...

If we need to elaborate about launching hardhat, we can add this in the [Hardhat template page](https://docs.zama.ai/fhevm/how-to/write_contract/hardhat). Like how to use mocks, how to start the docker image, etc etc... I wouldn't mix TFHE.cmux best practice in this section for example.

Finally, if we want to explain how to write a contract, we can write a full tutorial (writing without encryption and then write with Remix, then write in hardhat, then write test, ...). It could be a full video or an article.

2024-02-01 20:30 UTC, immortal-tofu commented on docs/SUMMARY.md
> +- [Typical workflow for writing confidential smart contracts](getting_started/workflow.md)
To remove, see comment below, sorry

2024-02-02 05:33 UTC, immortal-tofu requested changes

2024-02-02 05:33 UTC, immortal-tofu commented on docs/howto/write_contract.md
> +3/ Then launch an fhEVM local node with `pnpm fhevm:start` and start to add confidentiality by using the `TFHE` solidity library. Typically, this would involve converting some `uintX` types to `euint
```
When you're ready, you can start to add confidentiality by using the `TFHE` solidity library. Typically, this would involve converting some `uintX` types to `euintX`, as well as following all the detailed advices that we gave in the [pitfalls to avoid and best practises](../howto/pitfalls.md) section of the documentation. For inspiration, you can take a look at the examples inside the [`fhevm` repository](https://github.com/zama-ai/fhevm/tree/main/examples). If you're using the Hardhat template, read the advices that we gave in the [Hardhat section](./write_contract/hardhat.md).
```

2024-02-02 05:33 UTC, immortal-tofu commented on docs/howto/write_contract.md
> +1/ For quick prototyping of a specific feature, use the [Zama version of the Remix IDE](./write_contract/remix.md). This will let you quickly deploy a contract on the devnet via Metamask, and interac
```
For quick prototyping of a specific feature, use the [Zama version of the Remix IDE](./write_contract/remix.md). This will let you quickly deploy a contract on the devnet via Metamask, and interact easily with it throug the Remix UI.
Otherwise, for a bigger project, you should use our custom [`fhevm-hardhat-template` repository](https://github.com/zama-ai/fhevm-hardhat-template). Hardhat is a popular development environment for Solidity developers and will let you test and deploy your contracts to the fhEVM using TypeScript.
```

2024-02-02 05:33 UTC, immortal-tofu commented on docs/howto/write_contract.md
> +We present here a quick sketch of a typical workflow for writing confidential smart contracts on the fhEVM.
Remove this sentence ?

2024-02-02 05:33 UTC, immortal-tofu commented on docs/howto/write_contract.md
> +2/ A good first step is to start with an unencrypted version of the contract you want to implement, as you would usually do on a regular EVM chain. It is easier to reason first on cleartext variables
```
A good first step is to start with an unencrypted version of the contract you want to implement, as you would usually do on a regular EVM chain. It is easier to reason first on cleartext variables, before thinking on how to add confidentialy.
```

2024-02-02 05:33 UTC, immortal-tofu commented on docs/howto/write_contract/hardhat.md
> +When developing confidential contracts, we recommend to use first the mocked version of fhEVM for faster testing with `pnpm test:mock` and coverage computation via `pnpm coverage:mock`, this will lea
`But please keep in mind` => `However, keep in mind`

2024-02-02 05:33 UTC, immortal-tofu commented on docs/howto/write_contract/hardhat.md
> +Finally, always remember to test the final version of your contract on the real fhEVM with `pnpm test` before deployment.
```
It's essential to run tests of the final contract version using the real fhEVM. You can do this by running `pnpm test` before deployment.
```

2024-02-02 05:35 UTC, immortal-tofu commented
Once merged in main, you need to open a pull request for `release/0.3.x` to make the changes happen in the current documentation.

2024-02-02 09:27 UTC, jat9292 approved these changes

2024-02-02 09:32 UTC, immortal-tofu approved these changes

2024-02-02 09:33 UTC, merged