docs: update Readme.md
zama-ai/fhevm-solidity pull request #283
Opened 2024-02-06 13:58 UTC by yuxizama

- Reorganized existing content to follow the new structure
- Aligned all the header links and badges
- Added a table of contents
- Added a call-to-action for users to star the repo
- Checked all links and replaced outdated ones.
- Unified the formatting
- Updated the support banner
- Improved the overall content quality
- Added missing content where necessary
- Added more “resources” for each product
- Ensured wording is consistent throughout

2024-02-08 09:15 UTC, aquint-zama approved these changes
2 minor suggestion that you could feel free to ignore, otherwise looks good to me!

2024-02-08 09:15 UTC, aquint-zama commented on README.md
> +> ℹ️ Note: Solidity files are formatted with prettier.
you could use Github admonition

> [!NOTE]
> this is a note

2024-02-08 09:15 UTC, aquint-zama commented on README.md
> +> ⚠️ WARNING: Use this command to generate Solidity code and prettier result automatically!
you could use Github admonition

> [!WARNING]
> this is a warning

2024-02-08 09:15 UTC, yuxizama reviewed
Hey! 
Here are some questions left before finalizing the Readme pages. 
Thanks!

2024-02-08 09:15 UTC, yuxizama commented on README.md
> +### Main features
Is everything correct and up to date in the "main features" 
Also, we would like to only include main features here, so if there are some minor ones or less important ones, we can consider to remove it.

2024-02-08 09:15 UTC, yuxizama commented on README.md
> +### Development Guide
The development guide" is for contributing to the project ? 
We also have another section "contributing"  below and it says: 
```
There are two ways to contribute to the Zama fhEVM:
- [Open issues](https://github.com/zama-ai/fhevm/issues/new/choose) to report bugs and typos, or to suggest new ideas
- Request to become an official contributor by emailing hello@zama.ai.
```
Are they in conflict?

2024-02-08 09:15 UTC, yuxizama commented on README.md
Here the "Contributing" part

2024-02-08 09:20 UTC, aquint-zama commented on README.md
> +### Development Guide
No they aren't, it's two different ways:
- giving feedbacks/asking for features 
or
- contributing: sharing code for fixes/new features

2024-02-08 09:21 UTC, aquint-zama commented on README.md
> +### Development Guide
development guide, is more Developer/User guide

2024-02-08 09:22 UTC, aquint-zama commented on README.md
> +*Learn more about Concrete ML features in the [documentation](https://docs.zama.ai/fhevm).*
about **fhEVM** features

2024-02-08 09:24 UTC, aquint-zama commented on README.md
> +Full, comprehensive documentation is available here: [https://docs.zama.ai/concrete-ml](https://docs.zama.ai/fhevm).
link is CML one

2024-02-08 09:25 UTC, aquint-zama requested changes
some CML refs to update

2024-02-08 09:32 UTC, yuxizama commented on README.md
> +### Development Guide
I see!

2024-02-09 15:12 UTC, yuxizama commented
I've made some last few commits. 
May you check the change? @aquint-zama 
If all good we can merge this PR. 
Thanks!

2024-02-09 15:34 UTC, aquint-zama approved these changes

2024-02-13 16:47 UTC, merged