feat: added the oracle contracts and library
zama-ai/fhevm-solidity pull request #292
Opened 2024-02-22 11:59 UTC by jatZama

2024-02-23 10:56 UTC, immortal-tofu requested changes

2024-02-23 10:56 UTC, immortal-tofu commented on oracle/OraclePredeploy.sol
> +    function decryptTEST(uint256 requestID) external view onlyRelayer returns (uint32) {
Can we find another way? Having a function to remove in production is error prone. Maybe it's possible to have a contract which extends this oracle for testing purpose?

2024-02-23 10:56 UTC, immortal-tofu commented on oracle/OraclePredeploy.sol
> +    function decryptTEST(uint256 requestID) external view onlyRelayer returns (uint32) {
Also I'd stick to camel case `decryptTest`

2024-02-23 11:41 UTC, jatZama commented on oracle/OraclePredeploy.sol
> +    function decryptTEST(uint256 requestID) external view onlyRelayer returns (uint32) {
The problem is that I do not know how to do otherwise, as this would change the hardcoded address of the predploy inside the library... Is there another way to do decryption without using TFHE.decrypt?

2024-02-26 17:52 UTC, jatZama commented
Second commit fixes all issues previously discussed here and on slack : 
-  added custom address in constructor for owner of predeploy
-  put the `decryptTest` (name in camelcase now) function into a separate contract `OraclePredeployTest` extending the original `OraclePredeploy`
- put the constant address of the Predeploy inside a separate `PredeployAddress.sol` file.

2024-02-26 17:56 UTC, jatZama commented on oracle/OraclePredeploy.sol
> +    function decryptTEST(uint256 requestID) external view onlyRelayer returns (uint32) {
answered and fixed here https://github.com/zama-ai/fhevm/pull/292#issuecomment-1964758613

2024-02-27 11:02 UTC, immortal-tofu approved these changes

2024-02-27 11:03 UTC, merged