test: cover the different types of values in decryption
zama-ai/fhevm-solidity pull request #299
Opened 2024-03-01 15:00 UTC by youben11

2024-03-01 15:04 UTC, jatZama commented on examples/TestAsyncDecrypt.sol
> +        unchecked {
you dont need to keep the unchecked block here as you dont do any arithmetic operation in your added examples. in my example i did an addition with two other numbers, and i added an unchecked because TFHE operators are wrapping in case of an overflow

2024-03-01 15:04 UTC, jatZama commented on examples/TestAsyncDecrypt.sol
> +        unchecked {
Also where are the Javascript tests???

2024-03-04 17:52 UTC, jatZama requested changes

2024-03-04 17:52 UTC, jatZama commented on examples/TestAsyncDecrypt.sol
> +    function callbackBool(uint256 requestID, bool decryptedInput) public onlyOracle returns (bool) {
Please replace `uint256 requestID` by `uint256 /*requestID*/` to mute compilation warnings during testing, as you are not using this argument in this case (contrarily to what I did for `callbackUint32`)

2024-03-04 17:52 UTC, jatZama commented on examples/TestAsyncDecrypt.sol
> +    function callbackUint8(uint256 requestID, uint8 decryptedInput) public onlyOracle returns (uint8) {
Please replace `uint256 requestID` by `uint256 /*requestID*/` to mute compilation warnings during testing, as you are not using this argument in this case (contrarily to what I did for `callbackUint32`)

2024-03-04 17:52 UTC, jatZama commented on examples/TestAsyncDecrypt.sol
> +    function callbackUint16(uint256 requestID, uint16 decryptedInput) public onlyOracle returns (uint16) {
Please replace `uint256 requestID` by `uint256 /*requestID*/` to mute compilation warnings during testing, as you are not using this argument in this case (contrarily to what I did for `callbackUint32`)

2024-03-04 17:52 UTC, jatZama commented on examples/TestAsyncDecrypt.sol
> +    function callbackUint64(uint256 requestID, uint64 decryptedInput) public onlyOracle returns (uint64) {
Please replace `uint256 requestID` by `uint256 /*requestID*/` to mute compilation warnings during testing, as you are not using this argument in this case (contrarily to what I did for `callbackUint32`)

2024-03-04 17:52 UTC, jatZama commented on test/oracleDecrypt/testAsyncDecrypt.ts
> +        codeHash === '0x808db48789429e5f79adb9849400e0d01c5c0f017663f06c6b2ab48f2eeae10e' ||
when I tested locally, the correct hash on fhevm is this one : `0xeffeaf5a1d024a603edb1c812f198ad8de84ea0a9b2b5e275b71a49794304d12` , so correct here please.
Second hash is correct and corresponds to the mocked mode. But I would prefer that you inverse order in the comment if you wish to keep this order in the hash. So finally I would write something like : 

     if (
        codeHash === '0xeffeaf5a1d024a603edb1c812f198ad8de84ea0a9b2b5e275b71a49794304d12' ||
        codeHash === '0xab7f73c011a5db013d92c7025cdc48b4d416ed21cd4e1ab102c590b46f560b26'
      ) {
        // it is indeed the OraclePredploy because it codeHashes are matching on either fhevm node or on the hardhat node (mocked mode)

2024-03-05 09:51 UTC, youben11 commented on test/oracleDecrypt/testAsyncDecrypt.ts
> +        codeHash === '0x808db48789429e5f79adb9849400e0d01c5c0f017663f06c6b2ab48f2eeae10e' ||
working fine locally after the rebase on main

2024-03-05 10:15 UTC, jatZama approved these changes

2024-03-05 10:17 UTC, merged