update readme and fix some issues
zama-ai/fhevm-solidity pull request #310
Opened 2024-03-07 09:26 UTC by miles-six

I have been studying this repository for a long time, and whenever I come across a typo, I fix it. 

I discovered 7 typos in a total of 7 files. Then I merged them together.

The code quality is exceptionally high, so sincerely hope my PR can help make this repository more standardized.

2024-03-08 01:23 UTC, miles-six commented
I have singed CLA

2024-03-08 09:41 UTC, jatZama requested changes

2024-03-08 09:41 UTC, jatZama commented on docs/fundamentals/write_contract/README.md
> +2/ A good first step is to start with an unencrypted version of the contract you want to implement, as you would usually do on a regular EVM chain. It is easier to reason first on cleartext variables
Please correct to : `confidentiality`

2024-03-08 09:45 UTC, miles-six commented on docs/fundamentals/write_contract/README.md
> +2/ A good first step is to start with an unencrypted version of the contract you want to implement, as you would usually do on a regular EVM chain. It is easier to reason first on cleartext variables
Thank you,already down it

2024-03-08 09:47 UTC, jatZama commented on docs/fundamentals/write_contract/README.md
> +2/ A good first step is to start with an unencrypted version of the contract you want to implement, as you would usually do on a regular EVM chain. It is easier to reason first on cleartext variables
btw commit message must follow commitlint convention or else CI will fail.

2024-03-08 09:59 UTC, miles-six commented on docs/fundamentals/write_contract/README.md
> +2/ A good first step is to start with an unencrypted version of the contract you want to implement, as you would usually do on a regular EVM chain. It is easier to reason first on cleartext variables
Can you tell me how to follow commitlint convention？Thank you sir

2024-03-08 10:02 UTC, jatZama commented on docs/fundamentals/write_contract/README.md
> +2/ A good first step is to start with an unencrypted version of the contract you want to implement, as you would usually do on a regular EVM chain. It is easier to reason first on cleartext variables
typically you would start this commit with "docs: ..." see https://github.com/conventional-changelog/commitlint

2024-03-08 10:08 UTC, miles-six commented on docs/fundamentals/write_contract/README.md
> +2/ A good first step is to start with an unencrypted version of the contract you want to implement, as you would usually do on a regular EVM chain. It is easier to reason first on cleartext variables
Thank you again sir, already down,Thank you

2024-03-08 10:08 UTC, immortal-tofu commented
@cla-bot check

2024-03-08 10:35 UTC, miles-six commented
@cla-bot check

2024-03-08 10:36 UTC, miles-six commented on docs/fundamentals/write_contract/README.md
> +2/ A good first step is to start with an unencrypted version of the contract you want to implement, as you would usually do on a regular EVM chain. It is easier to reason first on cleartext variables
Sir, sorry again,I have signed CLA for many times,but it still failed. I don't why

2024-03-09 03:35 UTC, miles-six commented
@cla-bot check

2024-03-09 04:03 UTC, miles-six commented
@cla-bot check

2024-03-09 04:09 UTC, miles-six commented
![45a53c198beb620c7b53862b07f10fdc](https://github.com/zama-ai/fhevm/assets/66052478/ea63d7da-2bfa-4415-b1bb-dec216113ca8)
![df0a071f3844d8e45ac48654801a9ec3](https://github.com/zama-ai/fhevm/assets/66052478/256c3d33-34e9-4a0f-b3f0-964766a35111)
I have singed as the config, but I have failed again

2024-03-11 06:51 UTC, miles-six commented
@cla-bot check

2024-03-11 07:33 UTC, aquint-zama commented
Once the CLA is signed it's a manual process to update the CLA bot whitelist. I'll do it.

2024-03-11 07:36 UTC, miles-six commented
Thank your response sir @aquint-zama 

Because it hasn't been approved for a while, I have signed multiple copies of the CLA.

 I hope this won't affect you.

2024-03-11 07:37 UTC, aquint-zama commented
@cla-bot check

2024-03-11 07:38 UTC, aquint-zama commented
> Thank your response sir @aquint-zama
> 
> Because it hasn't been approved for a while, I have signed multiple copies of the CLA.
> 
> I hope this won't affect you.

No don't worry, everything is ok now.

2024-04-03 12:53 UTC, aquint-zama commented
updated in https://github.com/zama-ai/fhevm/pull/350

2024-04-03 14:29 UTC, aquint-zama commented
merged in #350

2024-04-03 14:29 UTC, closed without merging