feat: add ability to call eaddress decrypt asynchronously
zama-ai/fhevm-solidity pull request #349
Opened 2024-04-02 14:11 UTC by leventdem

2024-04-05 14:20 UTC, immortal-tofu approved these changes

2024-04-08 11:24 UTC, jatZama requested changes

2024-04-08 11:24 UTC, jatZama commented on codegen/templates.ts
> +    uint8 internal constant euint160_t = 7;
can you change this to eaddress please?

2024-04-08 11:24 UTC, jatZama commented on examples/TestAsyncDecrypt.sol
> +    function callbackAddress(uint256 /*requestID*/, uint160 decryptedInput) public onlyOracle returns (address) {
pleae change this to address instead of uint160

2024-04-08 11:24 UTC, jatZama commented on examples/TestAsyncDecrypt.sol
> +        xAddress = TFHE.asEaddress(797161134358056856230896843146392277790002887282);
input should be an address instead of uint160

2024-04-08 11:24 UTC, jatZama commented on mocks/TFHE.sol
> +    uint8 internal constant euint160_t = 7;
can you change this to eaddress please?

2024-04-08 11:24 UTC, jatZama commented on oracle/OraclePredeploy.sol
> +        uint160[] memory decryptedCt /*, bytes memory signatureKMS */
should be an array of addresses instead of uint160s

2024-04-08 23:14 UTC, immortal-tofu commented on oracle/OraclePredeploy.sol
> +        uint160[] memory decryptedCt /*, bytes memory signatureKMS */
Under the hood, everything is uint160. I think we should keep everything as uint160, but when we call the callback function, we should pass an array of address. For this, we should convert the received uint160 from the relayer to actual address.

Maybe something like `callbackCalldata = abi.encodePacked(callbackCalldata, abi.encode(address(uint160(decryptedCt[i]))));` would work?

2024-04-08 23:16 UTC, immortal-tofu commented on examples/TestAsyncDecrypt.sol
> +        xAddress = TFHE.asEaddress(797161134358056856230896843146392277790002887282);
Both should work. Probably we need :

```
    // Convert an address value to an encrypted asEaddress.
    function asEaddress(address value) internal pure returns (eaddress) {
        return eaddress.wrap(Impl.trivialEncrypt(uint160(value), Common.euint160_t));
    }
```

2024-04-08 23:18 UTC, immortal-tofu commented on codegen/templates.ts
> +    uint8 internal constant euint160_t = 7;
uint160_t is the type used in fhevm-go, in tfhe-rs and in the KMS. I'd prefer keep uint160_t.

2024-04-08 23:21 UTC, immortal-tofu commented
User shouldn't manipulate numbers when we talk about eaddress or decryption of eaddress. User needs these functions:
```
TFHE.asEaddress(0x028783f98...);

function myCallback(uint256 requestId, address[] memory decryptions) {
  ...
}
```
If it's missing we should add this. Under the hood, tfhe-rs/KMS/fhevm-go talk about uint160 but it's fine. We just do the conversion in TFHE.sol on the fly with `address(value)` or `uint160(value)`

2024-04-08 23:51 UTC, immortal-tofu commented on mocks/TFHE.sol
> +    uint8 internal constant euint160_t = 7;
This value is linked to the implementation in fhevm-go, where we only talk about uint160. I'd prefer keep uint160_t.

2024-04-09 12:43 UTC, merged