Feat: add array equality
zama-ai/fhevm-solidity pull request #385
Opened 2024-05-23 13:02 UTC by immortal-tofu

2024-05-23 13:47 UTC, jatZama requested changes
See my comments concerning missing require on length, early return and missing types.
In addition, adding some tests will be nice.

2024-05-23 13:47 UTC, jatZama commented on mocks/Impl.sol
> +            if (larray[i] != rarray[i]) result = false;
Nit: you can return; at the end of this line to save some gas

2024-05-23 13:47 UTC, jatZama commented on mocks/TFHE.sol
> +    function eq(euint4[] memory a, euint4[] memory b) internal pure returns (ebool) {
are we sure we don't want to support eq for ebool[] and eaddress[] as well? native eq for ebool is not supported but this is equivalent to not(xor(a,b))

2024-05-23 13:47 UTC, jatZama commented on mocks/TFHE.sol
> +        for (uint i = 0; i < a.length; i++) {
I think you need to add a require to ensure a.length is equal to b.length, because I assume the tx reverts in FHEVMLib precompile if lengths are unequal (to be checked).

2024-05-23 14:21 UTC, immortal-tofu commented on mocks/TFHE.sol
> +    function eq(euint4[] memory a, euint4[] memory b) internal pure returns (ebool) {
This is not implemented in tfhe-rs for 160bits. I didn't check for ebool, I'll take a look.

2024-05-23 14:22 UTC, immortal-tofu commented
> See my comments concerning missing require on length, early return and missing types. In addition, adding some tests will be nice.

I'll add some test when fhevm-go will be ready.

2024-05-28 13:44 UTC, dartdart26 approved these changes
Looks good!

The only thing that we need to fix is the requires as mentioned in one of my previous messages.

2024-05-28 13:44 UTC, dartdart26 commented on lib/Impl.sol
> +    function fheArrayEq(uint256[] memory larray, uint256[] memory rarray) external pure returns (uint256 result);
Nit: May rename to `lhs` and `rhs` as we already use it for other ops.

2024-05-28 13:44 UTC, dartdart26 commented on lib/TFHE.sol
> +        require(a.length != b.length, "Both arrays are not of the same size.");
As discussed offline, needs to be `==` in all overloads. :)

2024-05-28 15:20 UTC, dartdart26 commented on codegen/templates.ts
> +          rhs[i] = euint${inputBits}.unwrap(a[i]);
```suggestion
          rhs[i] = euint${inputBits}.unwrap(b[i]);
```

2024-05-29 09:43 UTC, jatZama commented on test/tfheOperations/manual.ts
> +  it('array of value eq euint4,euint4 true', async function () {
Can you add tests that would also return false?

2024-05-29 09:44 UTC, jatZama commented on examples/tests/TFHEManualTestSuite.sol
> +    function test_eq_array_4(bytes calldata a, bytes calldata b) public view returns (bool) {
Ideally I would also add here tests that take arrays with different argument, to avoid bad surprises.

2024-05-29 09:50 UTC, immortal-tofu commented on examples/tests/TFHEManualTestSuite.sol
> +    function test_eq_array_4(bytes calldata a, bytes calldata b) public view returns (bool) {
wdym?

2024-05-29 09:52 UTC, jatZama commented on examples/tests/TFHEManualTestSuite.sol
> +    function test_eq_array_4(bytes calldata a, bytes calldata b) public view returns (bool) {
You are currently only testing arrays with duplicated elements.

2024-05-29 10:43 UTC, jatZama approved these changes

2024-05-29 18:33 UTC, merged