docs: update structure
zama-ai/fhevm-solidity pull request #391
Opened 2024-06-10 12:27 UTC by immortal-tofu

2024-06-18 13:16 UTC, jatZama requested changes

2024-06-18 13:16 UTC, jatZama commented on docs/guides/decrypt.md
> +function getParamsUint(uint256 requestID) internal;
This function has been renamed `getParamsUint256`

2024-06-18 13:16 UTC, jatZama commented on docs/guides/decrypt.md
> +function addParamsUint(uint256 requestID, uint256 _uint) internal;
This function has been renamed `addParamsUint256`

2024-06-18 13:16 UTC, jatZama commented on docs/guides/decrypt.md
> +      addParamsUint(requestID, input1);
Same, rename it addParamsUint256

2024-06-18 13:16 UTC, jatZama commented on docs/guides/decrypt.md
> +      uint256 requestID = Gateway.requestDecryption(cts, this.callbackUint32.selector, 0, block.timestamp + 100);
You are missing the last boolean argument, which should be false in this case.
Please, see updated example with latest function signature here : https://github.com/zama-ai/coprocessor-contracts/blob/main/contracts/examples/TestAsyncDecrypt.sol

2024-06-18 13:16 UTC, jatZama commented on docs/guides/decrypt.md
> +      xUint32 = TFHE.asEuint32(32);
You forgot to allow xUint32 in the constructor.
Please, see updated example here : https://github.com/zama-ai/coprocessor-contracts/blob/main/contracts/examples/TestAsyncDecrypt.sol

2024-06-18 13:36 UTC, immortal-tofu commented on docs/guides/decrypt.md
> +      uint256 requestID = Gateway.requestDecryption(cts, this.callbackUint32.selector, 0, block.timestamp + 100);
I didn't change a line from decrypt documentation. I'll take a look

2024-06-18 13:39 UTC, jat9292 commented on docs/guides/decrypt.md
> +      uint256 requestID = Gateway.requestDecryption(cts, this.callbackUint32.selector, 0, block.timestamp + 100);
yes but as I said, you should, since API changed. Also by the way, cts should now be an array of uint256, not euint32[]. See my example file.

2024-06-18 13:55 UTC, jat9292 commented on docs/fundamentals/acl.md
> +When a function receives a ciphertext, it needs to verify that the sender also has access to this ciphertext. This is important because otherwise, a contract could send any ciphertext authorized for
Maybe I would be more specific here: "When a function receives a ciphertext handle type such as ebool, euintXX, ebytes256 or eaddress" to not confuse with the ehandle type for user inputs.

2024-06-18 14:00 UTC, jatZama commented on docs/guides/decrypt.md
> +    cts[0] = xBool;
Here, again, as I said previosuly , you need to pass a uint256[] array, so please use ```        uint256[] memory cts = new uint256[](1);
        cts[0] = Gateway.toUint256(xBool);```
See https://github.com/zama-ai/coprocessor-contracts/blob/main/contracts/examples/TestAsyncDecrypt.sol#L57C1-L58C43

2024-06-18 14:00 UTC, jatZama commented on docs/guides/decrypt.md
> +function requestDecryption(
The correct signature is now : ```    function requestDecryption(
        uint256[] calldata ctsHandles,
        bytes4 callbackSelector,
        uint256 msgValue,
        uint256 maxTimestamp,
        bool passSignaturesToCaller
    )```

2024-06-18 14:01 UTC, jatZama commented on docs/guides/decrypt.md
> +      cts[0] = xUint32;
Here also, use  Gateway.toUint256 please

2024-06-19 12:22 UTC, jatZama approved these changes

2024-06-19 12:28 UTC, merged