Adding templates for easier handling of customer support
zama-ai/fhevm-solidity pull request #544
Opened 2024-10-01 10:47 UTC by poppyseedDev

Added issue templates for bug reports for `fhevm`, `fhevmjs`, documentation, unclear documentation, a custom issue report and a more general feature request template.

2024-10-01 13:55 UTC, aquint-zama approved these changes
great initiative. Few comments, feel free to take them into account or not.

2024-10-01 13:55 UTC, aquint-zama commented on .github/ISSUE_TEMPLATE/custom.md
> +---
I don't think you need this one as you always have the option to open a blank issue

2024-10-01 13:55 UTC, aquint-zama commented on .github/ISSUE_TEMPLATE/bug_report_fhevm.md
> +title: '[BUG] - [Brief Description of Issue]'
maybe `[Bug] - [...]` format in the title is redundant with the bug label

2024-10-01 13:55 UTC, aquint-zama commented on .github/ISSUE_TEMPLATE/bug_report_fhevm.md
> +### **Smart Contract Code Snippet (Optional)**
you could make the code part foldable (if you want) see https://github.com/zama-ai/concrete/tree/main/.github/ISSUE_TEMPLATE

2024-10-01 13:55 UTC, aquint-zama commented on .github/ISSUE_TEMPLATE/bug_report_fhevmjs.md
> +title: '[BUG]'
same I would not include [BUG] in the title as it's already a label (but it's a team convention so I let you decide :wink:)

2024-10-01 13:55 UTC, aquint-zama commented on docs/fundamentals/types/README.md
> +When using encrypted types for state variables, you cannot use the `immutable` or `constant` keywords. This is because the compiler attempts to resolve the value of `TFHE.asEuintXX(yy)` during compil
neat picking: would be better in another commit (PR?)

2024-10-02 14:57 UTC, poppyseedDev commented on .github/ISSUE_TEMPLATE/bug_report_fhevm.md
> +### **Smart Contract Code Snippet (Optional)**
Oh waw! Nice thanks for the tip!

2024-10-03 05:19 UTC, poppyseedDev commented
@aquint-zama thanks for your suggestions! Last 2 commits modify the PR based on your them.

2024-10-08 07:46 UTC, yuxizama requested changes
Thank you for this initiative! @poppyseedDev 
Just one remark about the doc reports: Maybe we need to distinguish more the two, or merge them into 1. As in some occasion users can't know if it's a bug, or if it's a unclear explanation. 

Unclear Documentation Report | Use this template to report sections of our documentation that are unclear, confusing, or require further explanation.
-- | --

Documentation Bug Report | Use this template to report issues, inconsistencies, or inaccuracies in our documentation.
-- | --

WDYT?

2024-10-08 09:22 UTC, poppyseedDev commented
> Thank you for this initiative! @poppyseedDev Just one remark about the doc reports: Maybe we need to distinguish more the two, or merge them into 1. As in some occasion users can't know if it's a bug, or if it's a unclear explanation.
> 
> Unclear Documentation Report	Use this template to report sections of our documentation that are unclear, confusing, or require further explanation.
> Documentation Bug Report	Use this template to report issues, inconsistencies, or inaccuracies in our documentation.
> WDYT?

@yuxizama Hmm yes you are right, it would make sense to merge it into one.

2024-10-08 10:22 UTC, poppyseedDev commented
@yuxizama issue resolved, could you check re-check if everything is okay :) ?

2024-10-09 08:37 UTC, yuxizama approved these changes
Thank you! @poppyseedDev

2024-10-09 10:39 UTC, merged