chore: updates fhevmjs and fhevmjsMocked to v0.6
zama-ai/fhevm-solidity pull request #569
Opened 2024-10-09 21:37 UTC by jatZama

2024-10-09 22:35 UTC, immortal-tofu commented on test/instance.ts
> +const kmsAdd = dotenv.parse(fs.readFileSync('lib/.env.kmsverifier')).KMS_VERIFIER_CONTRACT_ADDRESS;
Maybe using dotenv package would be cleaner https://www.npmjs.com/package/dotenv

2024-10-09 22:39 UTC, immortal-tofu requested changes

2024-10-09 22:39 UTC, immortal-tofu commented on test/instance.ts
> +const kmsAdd = dotenv.parse(fs.readFileSync('lib/.env.kmsverifier')).KMS_VERIFIER_CONTRACT_ADDRESS;
Maybe use 

```
const kmsAdd = dotenv.config({ path: 'lib/.env.kmsverifier' }).KMS_VERIFIER_CONTRACT_ADDRESS;
const aclAdd = dotenv.config({ path: 'lib/.env.acl' }).ACL_CONTRACT_ADDRESS;
```

2024-10-09 22:39 UTC, immortal-tofu commented on test/instance.ts
> +    createEIP712: (publicKey: string, verifyingContract: string, delegatedAccount?: string) =>
Maybe rewrite as follow
```
createEIP712: createEIP712(network.config.chainId),
```

2024-10-10 08:44 UTC, immortal-tofu approved these changes

2024-10-10 08:45 UTC, jatZama commented on test/instance.ts
> +const kmsAdd = dotenv.parse(fs.readFileSync('lib/.env.kmsverifier')).KMS_VERIFIER_CONTRACT_ADDRESS;
i tried but was unsuccessful, will do this later in Q4.

2024-10-10 08:45 UTC, jatZama commented on test/instance.ts
> +    createEIP712: (publicKey: string, verifyingContract: string, delegatedAccount?: string) =>
done

2024-10-10 09:23 UTC, merged