Adds comments to example contracts, improve example contracts documentation
zama-ai/fhevm-solidity pull request #570
Opened 2024-10-10 08:22 UTC by poppyseedDev

Closes #555 
Mentions #556

2024-10-10 08:31 UTC, poppyseedDev commented
Note: there is a dead links error for https://github.com/zama-ai/fhevm/blob/main/examples/README.md, however this will not be an error anymore once this PR will be merged.

2024-10-10 09:12 UTC, jatZama commented
Firstly, can you rebase interactively and squash all your commits to get a unique clean commit instead of 14?

2024-10-10 09:13 UTC, jatZama commented on docs/tutorials/see-all-tutorials.md
> +- [Counter](https://github.com/zama-ai/fhevm/blob/main/examples/Counter.sol): A simple contract demonstrating basic state management with an incrementable counter.
We don't want to talk about all those (from Counter to ACLUpgradedExample]), which are just for internal testing. I would suggest you don't mention them.

2024-10-10 09:45 UTC, poppyseedDev commented on docs/tutorials/see-all-tutorials.md
> +- [Counter](https://github.com/zama-ai/fhevm/blob/main/examples/Counter.sol): A simple contract demonstrating basic state management with an incrementable counter.
Hmm as I was looking into them I think they still might be beneficial as additional examples for developers learning, that is why I would still leave the explanations the `README.md` file, however you are right they are not as curated as are the Blind Auction contract and the EncryptedERC-20 contract, maybe it would make sense to eventually differentiate between such curated contracts and others meant only for testing.

2024-10-10 11:24 UTC, jatZama commented on docs/tutorials/see-all-tutorials.md
> +- [Counter](https://github.com/zama-ai/fhevm/blob/main/examples/Counter.sol): A simple contract demonstrating basic state management with an incrementable counter.
As we disagree, let's ask @immortal-tofu for his opinion on this then.

2024-10-10 11:25 UTC, jatZama commented on docs/tutorials/see-all-tutorials.md
> +- [Counter](https://github.com/zama-ai/fhevm/blob/main/examples/Counter.sol): A simple contract demonstrating basic state management with an incrementable counter.
For me you can keep the 2 Legacy ones as they really use TFHE.sol features, but as I told you the Counter and other ones are unrelated to TFHE really, so they dont make sense to be mentionned.

2024-10-10 11:28 UTC, jatZama commented on docs/tutorials/see-all-tutorials.md
> +- [Counter](https://github.com/zama-ai/fhevm/blob/main/examples/Counter.sol): A simple contract demonstrating basic state management with an incrementable counter.
Maybe you coud keep EncryptedERC20, BlindAuction, and the TestAsyncDecrypt. But that's it, even the Rand one is to be discarded since it is not a realistic contract (use of the decrypt64 function in test).

2024-10-10 16:03 UTC, yuxizama requested changes, later dismissed

2024-10-10 16:03 UTC, yuxizama commented on examples/README.md
> +# fhEVM Smart Contract Examples
Hey @poppyseedDev, please use sentence-case capitalization for titles in the documentation.
For example, "Quick Overview" -> "Quick overview"
Thanks!

2024-10-14 07:50 UTC, poppyseedDev commented on docs/tutorials/see-all-tutorials.md
> +- [Counter](https://github.com/zama-ai/fhevm/blob/main/examples/Counter.sol): A simple contract demonstrating basic state management with an incrementable counter.
```suggestion
```

2024-10-14 07:51 UTC, poppyseedDev commented on docs/tutorials/see-all-tutorials.md
> +- [ACLUpgradedExample](https://github.com/zama-ai/fhevm/blob/main/examples/ACLUpgradedExample.sol): An upgraded version of the Access Control List (ACL) contract with version information.
```suggestion
```

2024-10-14 07:53 UTC, poppyseedDev commented on examples/README.md
> +# fhEVM Smart Contract Examples
```suggestion
# FhEVM smart contract examples
```

2024-10-14 07:53 UTC, poppyseedDev commented on examples/README.md
> +## Contract Summaries
```suggestion
## Contract summaries
```

2024-10-14 07:54 UTC, poppyseedDev commented on examples/README.md
> +## Quick Overview
```suggestion
## Quick overview
```

2024-10-14 08:40 UTC, poppyseedDev commented
> Firstly, can you rebase interactively and squash all your commits to get a unique clean commit instead of 14?

@jatZama I managed to squash only a portion of them, for the remaining few I get the following error:

Unable to squash. Squashing replays all commits up to the last one required for the squash. A merge commit cannot exist among those commits.

2024-10-14 08:43 UTC, poppyseedDev commented on examples/README.md
@jatZama related to our prior discussion - what is your opinion on the following `README.md`?

2024-10-14 08:44 UTC, poppyseedDev commented on examples/README.md
Do I remove some of the descriptions from here as well, or leave as is?

2024-10-14 08:45 UTC, jatZama commented on examples/README.md
how do you do the squash?
I use git rebase -i HEAD~X where X is the number of commits i want to squash

2024-10-14 08:46 UTC, jatZama commented
> > Firstly, can you rebase interactively and squash all your commits to get a unique clean commit instead of 14?
> 
> @jatZama I managed to squash only a portion of them, for the remaining few I get the following error:
> 
> Unable to squash. Squashing replays all commits up to the last one required for the squash. A merge commit cannot exist among those commits.

how do you do the squash?
I use `git rebase -i HEAD~X` where X is the number of commits i want to squash

2024-10-14 08:47 UTC, jatZama commented on examples/README.md
I don't think this internal Readme is important, since most of those tests are internal. Do as you whish. At least those should not be present in official Readme or docs

2024-10-14 09:34 UTC, poppyseedDev commented on examples/README.md
Unnecessary contracts removed

2024-10-17 09:16 UTC, yuxizama approved these changes
Thank you so much for the updates! 
@poppyseedDev 
Could you merge this PR also into the x0.5 branch? Otherwise it won't be reflected in the documentation website, especially in the "see-all-tutorials.md" where the links to "Governor DAO" and "Decentralized ID" are dead.

2024-10-22 13:04 UTC, merged