docs: fix due to change in hardhat-templates + README
zama-ai/fhevm-solidity pull request #642
Opened 2024-12-06 18:24 UTC by poppyseedDev

2024-12-06 18:27 UTC, immortal-tofu approved these changes

2024-12-10 22:11 UTC, poppyseedDev commented
@jatZama could you review:
 - docs/guides/debug_decrypt.md
 - docs/guides/gas.md
 - docs/guides/trivial_encrypt.md

2024-12-11 13:21 UTC, jatZama requested changes
I put many comments

2024-12-11 13:21 UTC, jatZama commented on README.md
> +  euint8 counter;
can you add `internal` here?

2024-12-11 13:21 UTC, jatZama commented on README.md
> +Here’s an improved and visually appealing version with enhanced styling and clarity:
as said on slack, maybe remove this sentence

2024-12-11 13:21 UTC, jatZama commented on README.md
> +### **Smart Contracts**
as said on slack, put first the hardhat-template section, and this one concerning fhevm-contracts second position instead.
"Hardhat template should really come first, and it is not in "Backend development" category
I would say instead maybe "Smart contracts testing and development"
and for the fhevm-contracts one, i would put it in second position, and under "Library of standardized fhEVM contracts" (not just smart contracts, since we want to incentivize developers to clearly use the hardhat template for developing the smart contracts with mocked mode)"

2024-12-11 13:21 UTC, jatZama commented on docs/fundamentals/decryption/decrypt.md
>      euint8 counter;
same, if you dont put a visibility modifier, then use `internal` instead of nothing maybe

2024-12-11 13:21 UTC, jatZama commented on docs/getting_started/first_smart_contract.md
>    euint8 counter;
same remark here, add internal

2024-12-11 13:21 UTC, jatZama commented on docs/getting_started/first_smart_contract.md
>    euint8 CONST_ONE;
and for this one you should even add the  `immutable` keyword to save gas, `euint8 immutable internal CONST_ONE;`

2024-12-11 13:21 UTC, jatZama commented on docs/guides/debug_decrypt.md
> +This guide explains how to use the `debug.decryptXX` functions for debugging encrypted data in mocked environments during development with fhEVM. These functions allow developers to decrypt encrypted
add an important remark such as: "this function sidesteps the need for any ACL authorization, allowing you to decrypt any ciphertext for debugging purpose" or something similar.

2024-12-11 13:21 UTC, jatZama commented on docs/guides/debug_decrypt.md
> +This guide explains how to use the `debug.decryptXX` functions for debugging encrypted data in mocked environments during development with fhEVM. These functions allow developers to decrypt encrypted
instead of `debug.decryptXX` maybe use something more explicit like "`debug.decrypt[XX]`, where XX should be replaced by the type you want to decrypt, for instance `debug.decrypt[XX]`. For instance `debug.decryptBool` to decrypt an ebool, and `debug.decrypt32` to decrypt a euint32, etc"

2024-12-11 13:21 UTC, jatZama commented on docs/guides/debug_decrypt.md
> +import { debug } from "./debug";
Wrong import here, it should be imorted from the `tests/utils.ts` from hardhat-template: https://github.com/zama-ai/fhevm-hardhat-template/blob/main/test/confidentialERC20/ConfidentialERC20.ts#L7

2024-12-11 13:21 UTC, jatZama commented on docs/guides/debug_decrypt.md
> +The `debug.decryptXX` functions allow you to decrypt encrypted handles into plaintext values. This feature is useful for debugging encrypted operations such as transfers, balance checks, and other co
Please add somewhere that this function should be imorted from the `tests/utils.ts` file from the hardhat-template repo

2024-12-11 13:21 UTC, jatZama commented on docs/guides/debug_decrypt.md
> +3. **Validate Inputs**:
imo this last point is obvious and not so important, but you can keep it if you want

2024-12-11 13:21 UTC, jatZama commented on docs/guides/frontend/webpack.md
> +**Possible solutions:** Use the prebundled version available in `fhevmjs/bundle`. Embed the library with a `<script>` tag and initialize it as shown below:
in the ` const instance = window.fhevm
    .createInstance({` snippet below, all values seem outdated, such as the gateway url and the contract addresses, etc can you put the correct values?

2024-12-11 13:21 UTC, jatZama commented on docs/guides/gas.md
> +   - Works in only in mocked fhEVM environments.
the helper function works only in mocked mode, but give the exact same value equal to the real one in non-mocked.

2024-12-11 13:21 UTC, jatZama commented on docs/guides/gas.md
> +1. **`getFHEGasFromTxReceipt`**:
please say where this helper is coming from: ie it should be imported from the `tests/coprocessorUtils.ts` file from hardhat-template as seen here https://github.com/zama-ai/fhevm-hardhat-template/blob/main/test/confidentialERC20/ConfidentialERC20.FHEGas.ts#L4

2024-12-11 13:21 UTC, jatZama commented on docs/guides/gas.md
> +2. **`.gasUsed`**:
this is a native value from ethers js tx receipts, nothing specific to fhevm, better to mention it precisely.

2024-12-11 13:21 UTC, jatZama commented on docs/guides/gas.md
> +```typescript
add at the top of this snippet an example declaration fot the `tx` by submitting a tx, otherwise it is not very clear

2024-12-11 13:21 UTC, jatZama commented on docs/guides/gas.md
> +const transaction = await tx.wait();
here for clarity it would be better to rename `transaction` variable to `receipt`

2024-12-11 13:21 UTC, jatZama commented on docs/guides/gas.md
> +   - Represents gas used for standard Ethereum operations.
say its coming from the native EVM on which coprocessor is being run, so nothing special about it

2024-12-11 13:21 UTC, jatZama commented on docs/guides/gas.md
> +2. **FHE Gas**:
rename it to single word "FHEGas"

2024-12-11 13:21 UTC, jatZama commented on docs/guides/gas.md
> +   - Represents gas consumed by FHE-specific computations.
say it is a new synthetic kind of gas, corresponding to a value being tracked in each block by the FHEPayment contract, to avoid DDOS if too many FHE operations are requested in same block, by reverting the tx once the FHEGas block limit is reached

2024-12-11 13:21 UTC, jatZama commented on docs/guides/gas.md
> +   - FHE gas is consistent across both mocked and real fhEVM environments.
FHEGas

2024-12-11 13:21 UTC, jatZama commented on docs/guides/gas.md
> +> **Note**: Gas values provided are approximate and may vary based on network conditions, implementation details, and contract complexity.
FHEGas, not gas

2024-12-11 13:21 UTC, jatZama commented on docs/guides/gas.md
> +The following code demonstrates how to measure both FHE gas and native gas during a transaction:
FHEGas in one word

2024-12-11 13:21 UTC, jatZama commented on docs/guides/gas.md
> +  const FHEGasConsumed = getFHEGasFromTxReceipt(transaction);
also show somewhere in the snippet how this function is imported from the `tests/coprocessorUtils.ts` file, see for eg:  https://github.com/zama-ai/fhevm-hardhat-template/blob/main/test/confidentialERC20/ConfidentialERC20.FHEGas.ts#L4

2024-12-11 13:21 UTC, jatZama commented on docs/guides/gas.md
> +The current devnet has a gas limit of **10,000,000**. Here's what you need to know:
not gas limit, FHEGas limit.

2024-12-11 13:21 UTC, jatZama commented on docs/guides/gas.md
> +- If you send a transaction that exceeds this limit:
add "or if the FHEGas block limit is exceeded, depending on other previous tx in same block"

2024-12-11 13:21 UTC, jatZama commented on docs/guides/gas.md
> +  - Your wallet will be unable to emit new transactions
those two points are WRONG remove them , because FHEGas is not like native gas: "
 - Your wallet will be unable to emit new transactions
  - You'll need to send a new transaction with the same nonce but correct gas limit"

2024-12-11 13:21 UTC, jatZama commented on docs/guides/gas.md
> +  - The transaction will fail to execute
this is not precise either, for first point, you should say "your transaction will revert" instead of "  - The transaction will fail to execute"
This is again a difference between coprocessor and native , because FHEGas is not native gas there

2024-12-11 13:21 UTC, jatZama commented on docs/guides/gas.md
> +Gas costs increase with the bit-width of the encrypted integer type. Below are the detailed costs for various operations on encrypted types.
FHEGas

2024-12-11 13:21 UTC, jatZama commented on docs/guides/gas.md
> +| Function name               | Gas fee         |
maybe replace all Gas with FHEGas, this way we get unified naming for both coprocessor and native

2024-12-11 13:21 UTC, jatZama commented on docs/guides/gas.md
> +  - Your wallet will be unable to emit new transactions
Actually those point would remain true only for fhevm native case, because in fhevm native, contrarily to coprocessor, FHEGas is part of native gas as well fyi. But dont say this for the moment, since fhevm0.6 only support the coprocessor model, native is no longer supported for the moment

2024-12-11 13:21 UTC, jatZama commented on docs/guides/trivial_encrypt.md
> +   Verify the padding and encryption in both mocked and real fhEVM environments to ensure correct behavior.
testing in mocked should be enough

2024-12-11 13:21 UTC, jatZama commented on docs/guides/trivial_encrypt.md
> +# **Trivial encryption of `ebytesXX` types**
This is a bit hard to follow without context. I would add a first section on how to do "easy trivial encryption" for the other types (ie from ebool to euint256, you dont need to do any padding, since those are value types of fixed size in solidity, contrarily to bytes types)

2024-12-11 13:21 UTC, jatZama commented on docs/guides/trivial_encrypt.md
> +# **Trivial encryption of `ebytesXX` types**
i.e you just need to do TFHE.asEbool(x) or TFHE.asEaddress(x) or TFHE.asEuintXX for those easy types - show it in a first section, otherwise this new section wont make much sense by itself imo

2024-12-11 13:21 UTC, jatZama commented on docs/guides/trivial_encrypt.md
> +# **Trivial encryption of `ebytesXX` types**
VERY IMPORTANT: explain somewhere what trivialEncrypt is about (it is for "casting" a plaintext to a ciphertext, to make it available/compatible with the TFHE operators, but it doesnt hide anything about this value, since it remains public from the blockchain)

2024-12-11 14:01 UTC, poppyseedDev commented on docs/guides/debug_decrypt.md
> +This guide explains how to use the `debug.decryptXX` functions for debugging encrypted data in mocked environments during development with fhEVM. These functions allow developers to decrypt encrypted
the types are specified later on.

2024-12-11 14:02 UTC, jatZama commented on docs/guides/debug_decrypt.md
> +This guide explains how to use the `debug.decryptXX` functions for debugging encrypted data in mocked environments during development with fhEVM. These functions allow developers to decrypt encrypted
I know, but the way this sentence is written now, some readers might believe the function that you are describing is really called decryptXX

2024-12-11 14:48 UTC, poppyseedDev commented on docs/guides/trivial_encrypt.md
> +# **Trivial encryption of `ebytesXX` types**
Continuing from the [types page and casting section](../fundamentals/types.md), this guide covers trivial encryption for `ebytesXX` types.

2024-12-11 14:49 UTC, poppyseedDev commented on docs/guides/trivial_encrypt.md
> +# **Trivial encryption of `ebytesXX` types**
# **Trivial encryption of `ebytesXX` types**

This guide explains how to perform trivial encryption of `ebytesXX` types in fhEVM smart contracts using the new `padToBytesXX` functions. These functions ensure that byte arrays are correctly padded to match the required sizes for `ebytes64`, `ebytes128`, and `ebytes256` types. Continuing from the [types page and casting section](../fundamentals/types.md), this guide covers trivial encryption for `ebytesXX` types.

---

## **Overview**

Trivial encryption is a process that converts plaintext values into encrypted types (ciphertexts) that are compatible with TFHE operators, without actually hiding the data. The resulting ciphertext remains publicly visible on the blockchain - this is useful when you need to perform operations between public and private values using TFHE operators.

The `TFHE.padToBytesXX` functions facilitate this trivial encryption process for byte arrays, ensuring compatibility with `ebytesXX` types. These functions:

- Pad the provided byte array to the appropriate length (`64`, `128`, or `256` bytes).
- Prevent runtime errors caused by improperly sized input data.
- Work seamlessly with `TFHE.asEbytesXX` for trivial encryption.

> **Important**: Trivial encryption does NOT provide any privacy guarantees. The input data remains fully visible on the blockchain. Only use trivial encryption when working with public values that need to interact with actual encrypted data.

2024-12-11 15:03 UTC, jatZama commented on README.md
> +  Smart contracts testing and development
Can you be more specific here and add something like "this should be the primary entry point for developers wanting to develop smart contracts on fhEVM"?

2024-12-11 15:05 UTC, jatZama commented on docs/guides/gas.md
> +> **Note**: FHEGas values provided are approximate and may vary based on network conditions, implementation details, and contract complexity.
Keep native gas here, not FHEGas.

2024-12-11 15:07 UTC, jatZama commented on docs/guides/gas.md
>  if (network.name === "hardhat") {
add a comment here to explain why we check this `if` condition , such as "// the `getFHEGasFromTxReceipt` util function only works in when testing in mocked mode"

2024-12-11 15:07 UTC, jatZama commented on docs/guides/gas.md
> +  is exceeded, depending on other previous tx in same block:
replace "tx" by "transactions" here please

2024-12-11 15:08 UTC, jatZama commented on docs/guides/gas.md
> +  - Any gas fees paid will still be charged
"Any native gas fees (but not FHEGas) will still be charge"

2024-12-11 15:09 UTC, jatZama commented on docs/guides/gas.md
> +  - Any gas fees paid will still be charged
Note this is only specific to coprocessor (but this is just fyi, since native is not part of docs now)

2024-12-11 15:10 UTC, poppyseedDev commented on docs/guides/gas.md
>  if (network.name === "hardhat") {
but it's mentioned 3 times in the documentation

2024-12-11 15:37 UTC, jatZama commented on docs/guides/gas.md
>  if (network.name === "hardhat") {
in a code snippet? i dont see it in the code unless i missed something, perhaps it is better to show it explicitly also in the code as a comment for improved clarity imho

2024-12-11 15:38 UTC, jatZama commented on docs/guides/gas.md
>  if (network.name === "hardhat") {
Otherwise I don't think it is straightforward for newcomers devs to understand immediately that if network name is "hardhat" this is equivalent to use mocked mode. So it makes more sense to include this small comment here.

2024-12-11 15:39 UTC, jatZama commented on docs/guides/gas.md
>  if (network.name === "hardhat") {
Maybe you can change the comment to something like "if network name is "hardhat" this means we are running the test in mocked mode" if you prefer this version

2024-12-11 16:54 UTC, yuxizama requested changes
Some minor details.
Please ping me again when the trivial_encrypt.md is finalized
Thx!

2024-12-11 16:54 UTC, yuxizama commented on docs/guides/debug_decrypt.md
> +### Key Points:
```suggestion
### Key points
```

2024-12-11 16:54 UTC, yuxizama commented on docs/guides/debug_decrypt.md
> +This guide explains how to use the `debug.decrypt[XX]` functions for debugging encrypted data in mocked environments during development with fhEVM. These functions allow developers to decrypt encrypt
```suggestion
This guide explains how to use the `debug.decrypt[XX]` functions for debugging encrypted data in mocked environments during development with fhEVM. 

> [!WARNING]  
> The `debug.decrypt[XX]` functions should not be used in production as they rely on private keys.
```

2024-12-11 16:54 UTC, yuxizama commented on docs/guides/debug_decrypt.md
> +- **Bypass ACL authorization**: The `debug.decrypt[XX]` functions allow decryption without ACL authorization, useful for verifying encrypted operations during development and testing.
```suggestion
- **Environment**: The `debug.decrypt[XX]` functions work **only in mocked environments** (e.g., `hardhat` network).
- **Production limitation**: In production, decryption is performed asynchronously via the Gateway and requires an authorized onchain request.
- **Encrypted types**: The `debug.decrypt[XX]` functions supports various encrypted types, including integers, booleans, and `ebytesXX`.
- **Bypass ACL authorization**: The `debug.decrypt[XX]` functions allow decryption without ACL authorization, useful for verifying encrypted operations during development and testing.
```

2024-12-11 16:54 UTC, yuxizama commented on docs/guides/debug_decrypt.md
> +---
```suggestion
```

2024-12-11 16:54 UTC, yuxizama commented on docs/guides/debug_decrypt.md
> +---
```suggestion

```

2024-12-11 16:54 UTC, yuxizama commented on docs/guides/debug_decrypt.md
> +## Function Usage
```suggestion
## Function usage
```

2024-12-11 16:54 UTC, yuxizama commented on docs/guides/debug_decrypt.md
> +> To utilize the debug functions, import the [utils.ts](https://github.com/zama-ai/fhevm-hardhat-template/blob/main/test/utils.ts) file.
```suggestion
> [!NOTE]  
> To utilize the debug functions, import the [utils.ts](https://github.com/zama-ai/fhevm-hardhat-template/blob/main/test/utils.ts) file.
```

2024-12-11 16:54 UTC, yuxizama commented on docs/guides/debug_decrypt.md
> +---
```suggestion

```

2024-12-11 16:54 UTC, yuxizama commented on docs/guides/debug_decrypt.md
> +The functions only work in the `hardhat` network. Attempting to use them in a production environment will result in an error.
```suggestion
> [!CAUTION]
> The functions only work in the `hardhat` network. Attempting to use them in a production environment will result in an error.
```

2024-12-11 16:54 UTC, yuxizama commented on docs/guides/debug_decrypt.md
> +---
```suggestion

```

2024-12-11 16:54 UTC, yuxizama commented on docs/guides/debug_decrypt.md
> +## **Best Practices**
```suggestion
## **Best practices**
```

2024-12-11 16:54 UTC, yuxizama commented on docs/guides/debug_decrypt.md
> +   For production, always use the asynchronous Gateway-based decryption.
```suggestion
- **Use only for debugging**: These functions require access to private keys and are meant exclusively for local testing and debugging.
- **Production decryption**: For production, always use the asynchronous Gateway-based decryption.
```

2024-12-11 16:54 UTC, yuxizama commented on docs/guides/frontend/webpack.md
> +2. If you encounter any other issue, you can force import of the browser package.
```suggestion
- If you encounter issues with typing, you can use this [tsconfig.json](https://github.com/zama-ai/fhevmjs-react-template/blob/main/tsconfig.json) using TypeScript 5.
- If you encounter any other issue, you can force import of the browser package.
```

2024-12-11 16:54 UTC, yuxizama commented on docs/guides/gas.md
> +2. **FHEGas**:
Is it in purpose that there's not a space in between FHE and Gas? 
Also should the G be capitalized?

2024-12-11 16:54 UTC, yuxizama commented on docs/guides/gas.md
> +> **Note**: FHEGas values provided are approximate and may vary based on network conditions, implementation details, and contract complexity.
```suggestion
> [!NOTE]  
>  FHEGas values provided are approximate and may vary based on network conditions, implementation details, and contract complexity.
```

2024-12-11 16:54 UTC, yuxizama commented on docs/guides/gas.md
> +1. **`getFHEGasFromTxReceipt`**:
```suggestion
- **`getFHEGasFromTxReceipt`**:
```

2024-12-11 16:54 UTC, yuxizama commented on docs/guides/gas.md
> +2. **`.gasUsed` from ethers.js transaction receipt**:
```suggestion
- **`.gasUsed` from ethers.js transaction receipt**:
```

2024-12-11 16:54 UTC, yuxizama commented on docs/guides/gas.md
> +### Boolean Operations (`ebool`)
```suggestion
### Boolean operations (`ebool`)
```

2024-12-11 16:54 UTC, yuxizama commented on docs/guides/gas.md
> +  - You should either:
```suggestion
  - You should do one of the following:
```

2024-12-11 19:23 UTC, poppyseedDev commented on docs/guides/gas.md
>  if (network.name === "hardhat") {
ok

2024-12-11 19:27 UTC, jatZama commented on docs/fundamentals/asXXoperation.md
> +This documentation covers the `asEbool`, `asEuintXX`, and `asBytesXX` operations provided by the TFHE library for working with encrypted data in the fhEVM. These operations are essential for converti
should be asEbool, asEuintXX and as EbBtesXX, both asEuintXX and as EBytesXX are wrong in the title, and asEbytes in the text as well

2024-12-11 19:30 UTC, poppyseedDev commented on README.md
> +  Smart contracts testing and development
```suggestion
  Smart contracts testing and development <- primary entry point for developers wanting to develop smart contracts on fhEVM
```

2024-12-11 19:30 UTC, jatZama commented on docs/SUMMARY.md
> +- [asEbool, asUintXX and asBytesXX operations](fundamentals/asXXoperation.md.md)
change to `asEbool, asEuintXX and asEbytesXX` please

2024-12-11 19:32 UTC, jatZama commented on docs/fundamentals/asXXoperation.md
> +# asEbool, asUintXX and asBytesXX operations
Wdyt about renaming the folder  `asE[type]operator.md`?

2024-12-11 19:33 UTC, jatZama commented on README.md
> +    euint32 value = TFHE.asEuint8(valueInput, inputProof);
please change the type of value also to `euint8 value = ...`

2024-12-11 19:34 UTC, jatZama commented on README.md
> +Master `fhEVM` and build smarter contracts using these resources:
typo here `samrter` -> `smart`

2024-12-11 19:35 UTC, leventdem commented on docs/fundamentals/asXXoperation.md
> +Trivial input simply put is a plain text in a format of a cyphertext.
```suggestion
Trivial input simply puts plaintext into ciphertext format.
```

2024-12-11 19:38 UTC, poppyseedDev commented on docs/guides/frontend/webpack.md
> +**Possible solutions:** Use the prebundled version available in `fhevmjs/bundle`. Embed the library with a `<script>` tag and initialize it as shown below:
can add an issue that in the future https://github.com/zama-ai/fhevm/issues/650

2024-12-11 19:40 UTC, poppyseedDev commented on docs/guides/gas.md
> +2. **FHEGas**:
I don't mind - @jatZama suggestion

2024-12-11 19:41 UTC, jatZama commented on docs/guides/gas.md
> +2. **FHEGas**:
yes it is on purpose to really reduce any confusion possible with regular gas.

2024-12-11 19:45 UTC, jatZama commented on README.md
> +  Smart contracts testing and development <- primary entry point for developers wanting to develop smart contracts on fhEVM
can you put the last part with the arrow in bold and italic? I think it would make it even clearer. We really want to avoid many support questions from new devs not understanding how to start and trying directly to run tests from fhevm repo instead of hardhat-template.

2024-12-11 19:46 UTC, jatZama commented on README.md
>  It is available here: [fhevm-go](https://github.com/zama-ai/fhevm-go)
I am not sure fhevm-go is still maintained, maybe you should change this to point to fhevm-backend. wdyt @immortal-tofu @leventdem

2024-12-11 19:52 UTC, jatZama commented on docs/fundamentals/asXXoperation.md
> +## 1. Trivial input
Should be "Trivial Encryption" everywhere, not trivial input

2024-12-11 19:52 UTC, jatZama commented on docs/fundamentals/asXXoperation.md
> +> **Note**: When doing trivial encrypt, the data is made compatible with FHE operations but remains publicly visible on-chain unless explicitly encrypted.
trivial encrypt*ion*

2024-12-11 19:54 UTC, jatZama commented on docs/fundamentals/asXXoperation.md
> +   Use `TFHE.allowThis` and `TFHE.allow` to define access control for the encrypted data.
"3. Optionally, if you want to persist allowance for those variables for later use, ..."

2024-12-11 19:57 UTC, jatZama commented on docs/fundamentals/asXXoperation.md
> +| `euintX`  | `ebool`  | `TFHE.asEboolXX` |
It is wrong. Please remove this line: casting from euintXX to ebool (contrarily to the opposite direction, ebool to euintX is good, keep it) is not supported and ill defined, since different languages do it in different manners. If you really want to convert a euintX to an ebool, you could use TFHE.Ne for instance. As suggested in TFHEExecutor comment already , see comment at the end of this line https://github.com/zama-ai/fhevm-backend/blob/main/contracts/contracts/TFHEExecutor.sol#L492

2024-12-11 19:57 UTC, poppyseedDev commented on docs/fundamentals/asXXoperation.md
> +# asEbool, asUintXX and asBytesXX operations
this will f** up the gitbook

2024-12-11 19:58 UTC, poppyseedDev commented on docs/fundamentals/asXXoperation.md
> +## 1. Trivial input
we had a discussion with Levent on this it's a bit easier to clasify

2024-12-11 19:59 UTC, jatZama commented on docs/fundamentals/asXXoperation.md
> +|                          | `TFHE.asEbool(x)`       | `euintXX`         | `ebool`     |
this TFHE.asEbool(x) with euintXX as input is wrong once again, and should be removed. We cannot cast to ebool

2024-12-11 19:59 UTC, poppyseedDev commented on docs/fundamentals/asXXoperation.md
> +## 1. Trivial input
or you know what yeah will just convert to trivial encrypt

2024-12-11 20:02 UTC, jatZama commented on docs/fundamentals/asXXoperation.md
> +|                          | `TFHE.asEbool(x, y)`    | `einput`,proof    | `ebool`     |
I would keep the `bytes` somewhere as second arguments for all those functions.  `einput, bytes proof` for eg

2024-12-11 20:02 UTC, poppyseedDev commented on README.md
> +  Smart contracts testing and development <- primary entry point for developers wanting to develop smart contracts on fhEVM
but the README is not the primary entry point

2024-12-11 20:02 UTC, jatZama commented on docs/fundamentals/asXXoperation.md
> +| Trivial input            | `TFHE.asEuintXX(x)`     | `uintX`           | `euintX`    |
btw you forgot the eaddress type here, which is supported for trivial encryption and encrypted input (but not casting)

2024-12-11 20:03 UTC, poppyseedDev commented on README.md
> +  Smart contracts testing and development <- primary entry point for developers wanting to develop smart contracts on fhEVM
if https://github.com/zama-ai/fhevm -> is the primary entry point we have communication issues elsewhere

2024-12-11 20:03 UTC, jatZama commented on docs/fundamentals/asXXoperation.md
> +| Trivial input            | `TFHE.asEuintXX(x)`     | `uintX`           | `euintX`    |
I would use `Trivial encryption` everywhere in place of `Trivial innput`

2024-12-11 20:36 UTC, poppyseedDev commented on README.md
> +    euint32 value = TFHE.asEuint8(valueInput, inputProof);
```suggestion
    euint8 value = TFHE.asEuint8(valueInput, inputProof);
```

2024-12-11 20:36 UTC, poppyseedDev commented on README.md
> +Master `fhEVM` and build smarter contracts using these resources:
```suggestion
Master `fhEVM` and build smart contracts using these resources:
```

2024-12-11 20:38 UTC, poppyseedDev commented on README.md
> +  Smart contracts testing and development <- primary entry point for developers wanting to develop smart contracts on fhEVM
```suggestion
  Smart contracts testing and development <- ***primary entry point for developers wanting to develop smart contracts on fhEVM***
```

2024-12-11 20:38 UTC, jatZama commented on docs/SUMMARY.md
> +- [asEbool, asUintXX and asEBytesXX operations](fundamentals/asXXoperation.md)
you forgot to correct the typo here: asUintXX -> asEuintXX. Maybe you can also add asEaddress as well

2024-12-11 20:38 UTC, jatZama commented on docs/fundamentals/asXXoperation.md
> +# asEbool, asUintXX and asEbytesXX operations
same here, replace asUintXX with asEuintXX, and add asEaddress

2024-12-11 20:39 UTC, poppyseedDev commented on README.md
>  It is available here: [fhevm-go](https://github.com/zama-ai/fhevm-go)
```suggestion
```

2024-12-11 20:39 UTC, jatZama commented on docs/fundamentals/asXXoperation.md
> +## 1. Trivial input
as you wish, but I think Trivial encryption makes more sense because few lines earlier you already used trivial encryption, so let's not use different terminologies for same concept

2024-12-11 20:41 UTC, poppyseedDev commented on docs/fundamentals/asXXoperation.md
> +> **Note**: When doing trivial encrypt, the data is made compatible with FHE operations but remains publicly visible on-chain unless explicitly encrypted.
```suggestion
> **Note**: When doing trivial encryption, the data is made compatible with FHE operations but remains publicly visible on-chain unless explicitly encrypted.
```

2024-12-11 20:42 UTC, poppyseedDev commented on docs/fundamentals/asXXoperation.md
> +   Use `TFHE.allowThis` and `TFHE.allow` to define access control for the encrypted data.
```suggestion
   Use `TFHE.allowThis` and `TFHE.allow`optionally, if you want to persist allowance for those variables for later use.
```

2024-12-11 20:42 UTC, poppyseedDev commented on docs/fundamentals/asXXoperation.md
> +## 3. Encrypted input
```suggestion
## 3. Encrypted encrypt
```

2024-12-11 20:43 UTC, poppyseedDev commented on docs/fundamentals/asXXoperation.md
> +| Trivial input            | `TFHE.asEuintXX(x)`     | `uintX`           | `euintX`    |
```suggestion
| Trivial encrypt            | `TFHE.asEuintXX(x)`     | `uintX`           | `euintX`    |
```

2024-12-11 20:49 UTC, poppyseedDev commented on docs/fundamentals/asXXoperation.md
> +| `euintX`  | `ebool`  | `TFHE.asEboolXX` |
```
    // Cast an encrypted integer from euint8 to ebool.
    function asEbool(euint8 value) internal returns (ebool) {
        return ne(value, 0);
    }
```

2024-12-11 20:49 UTC, poppyseedDev commented on docs/fundamentals/asXXoperation.md
> +| `euintX`  | `ebool`  | `TFHE.asEboolXX` |
you have function definitions like so in the code

2024-12-11 20:52 UTC, jatZama commented on docs/fundamentals/asXXoperation.md
> +| `euintX`  | `ebool`  | `TFHE.asEboolXX` |
ah good catch, but as you see since this is using ne under the hood i forgot we abstracted away in TFHE. My bad, you can keep it, i had confusion because i thought about the TFHEExecutor implementation instead

2024-12-11 20:54 UTC, poppyseedDev commented on docs/fundamentals/asXXoperation.md
> +| Encrypted input          | `TFHE.asEuintXX(x, y)`  | `einput`, proof   | `euintX`    |
```suggestion
| Encrypted input          | `TFHE.asEuintXX(x, y)`  | `einput`, `bytes` proof   | `euintX`    |
```

2024-12-11 20:54 UTC, poppyseedDev commented on docs/fundamentals/asXXoperation.md
> +|                          | `TFHE.asEbool(x, y)`    | `einput`,proof    | `ebool`     |
```suggestion
|                          | `TFHE.asEbool(x, y)`    | `einput`, `bytes` proof    | `ebool`     |
```

2024-12-11 20:57 UTC, jatZama commented on docs/fundamentals/asXXoperation.md
> +|                          | `TFHE.asEbytesXX(x, y)` | `einput`,proof    | `ebytesXX`  |
last line also add the `bytes` before proof (please apply the change yourself, you can stop suggesting me many commits for each line, i might miss some and have to work on some other stuff)

2024-12-11 21:28 UTC, yuxizama approved these changes

2024-12-11 21:37 UTC, jatZama commented on docs/fundamentals/asXXoperation.md
> +
also add here address -> eaddress, this is possible for trivial encryption fyi

2024-12-11 21:38 UTC, jatZama commented on docs/fundamentals/asXXoperation.md
> +This documentation covers the `asEbool`, `asEuintXX`, and `asEbytesXX` operations provided by the TFHE library for working with encrypted data in the fhEVM. These operations are essential for convert
also add mention of asEaddress here please

2024-12-11 21:38 UTC, jatZama commented on docs/fundamentals/asXXoperation.md
> +|                          | `TFHE.asEbytesXX(x)`    | `bytesXX`               | `ebytesXX`  |
same here, in trivial encryption part of the table, add eadress

2024-12-11 21:39 UTC, jatZama commented on docs/fundamentals/asXXoperation.md
> +# asEbool, asEuintXX, asEaddress and asEbytesXX operations
I would have renamed this file `asEXXoperators.md`

2024-12-11 21:44 UTC, jatZama commented on docs/guides/gas.md
> +| `ifThenElse`                | 43,000-300,000  |
rename this "ifThenElse" to `"select" (for ebytes)` - in this case the higher prices are only for ebytes.

2024-12-11 22:11 UTC, jatZama approved these changes

2024-12-11 22:25 UTC, merged